services:
  database:
    image: mysql:latest
    networks:
      - test-network
    environment:
       MYSQL_ROOT_PASSWORD: dev
       MYSQL_DATABASE: e-commerce
    ports:
      - "3307:3306"
    volumes:
      - db:/var/lib/mysql
  app:
    build: .
    ports:
      - "8082:8082"
    networks:
      - test-network
    depends_on:
      - database

networks:
  test-network:
    driver: bridge

volumes:
  db: